// Generated by tools/generate_address_library_manifest.py. Do not edit.
#pragma once

#include <array>
#include <cstdint>
#include <string_view>

namespace kcd2o
{
    struct address_library_identity
    {
        std::string_view distribution;
        std::string_view build_key;
        std::uint32_t format_version;
        std::uint32_t entry_count;
        std::string_view sha256;
    };

    inline constexpr std::array supported_address_libraries{
        address_library_identity{"epic", "release_1_5-15693", 1U, 1369015U, "8e70a14bd0699ecd237773afd207e0ae41ed2fed7a2e3412dc6efcde79e00df4"},
        address_library_identity{"gog", "release_1_5-15693", 1U, 1360759U, "5dafd046172c5340f271339247a747ee4169d92b0639075bb8f1c5341554ec48"},
        address_library_identity{"steam", "release_1_5-15693", 1U, 1388086U, "9a992aa21d9046c1f1c67b8fbc54a51f63adea2c5ba692d7b15e6bfc4760f06c"},
    };
}
