#!/usr/bin/env python3
"""Generate the compile-time allowlist for vendored KCSE address tables."""

from __future__ import annotations

import argparse
import hashlib
import re
import struct
import sys
from pathlib import Path

HEADER = struct.Struct("<4sIII")
RECORD = struct.Struct("<II")
NAME = re.compile(r"^kcd_addresslib_(steam|gog|epic)_(.+)\.bin$", re.IGNORECASE)
EXPECTED_DISTRIBUTIONS = {"steam": 1, "gog": 2, "epic": 3}


def render(project_root: Path) -> str:
    directory = (
        project_root
        / "vendor"
        / "Address-Library-For-KCSE"
        / "kcd2_address_library"
    )
    entries = []
    for path in sorted(directory.glob("kcd_addresslib_*.bin")):
        match = NAME.fullmatch(path.name)
        if match is None:
            raise RuntimeError(f"invalid Address Library filename: {path.name}")
        data = path.read_bytes()
        if len(data) < HEADER.size:
            raise RuntimeError(f"truncated Address Library header: {path.name}")
        magic, format_version, distribution, count = HEADER.unpack_from(data)
        name = match.group(1).lower()
        expected_size = HEADER.size + count * RECORD.size
        if (
            magic != b"KASL"
            or format_version == 0
            or distribution != EXPECTED_DISTRIBUTIONS[name]
            or count == 0
            or len(data) != expected_size
        ):
            raise RuntimeError(f"invalid Address Library table: {path.name}")
        entries.append(
            (
                name,
                match.group(2),
                format_version,
                count,
                hashlib.sha256(data).hexdigest(),
            )
        )
    if not entries:
        raise RuntimeError(f"no Address Library tables found in {directory}")

    rows = "\n".join(
        '        address_library_identity{{"{}", "{}", {}U, {}U, "{}"}},'.format(
            *entry
        )
        for entry in entries
    )
    return f'''// Generated by tools/generate_address_library_manifest.py. Do not edit.
#pragma once

#include <array>
#include <cstdint>
#include <string_view>

namespace kcd2o
{{
    struct address_library_identity
    {{
        std::string_view distribution;
        std::string_view build_key;
        std::uint32_t format_version;
        std::uint32_t entry_count;
        std::string_view sha256;
    }};

    inline constexpr std::array supported_address_libraries{{
{rows}
    }};
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = args.project_root.resolve()
    output = root / "src" / "multiplayer" / "address_library_manifest.generated.hpp"
    try:
        expected = render(root)
        if args.check:
            if not output.is_file() or output.read_text(encoding="utf-8") != expected:
                print(
                    "ERROR: Address Library manifest is stale; run "
                    "tools/generate_address_library_manifest.py",
                    file=sys.stderr,
                )
                return 1
        else:
            output.write_text(expected, encoding="utf-8", newline="\n")
    except (OSError, RuntimeError, struct.error) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
